// Code generated by "sqlbgen type History generated ID type Tag generated ID -- lochis.gen.go"; DO NOT EDIT.

package main

import (
	"database/sql"
	"fmt"
)

func _() {
	// Validate the struct fields haven't changed. If this doesn't compile you probably need to `go generate` again.
	var h History
	_ = History{h.ID, h.Time, h.Speed, h.Altitude, h.Latitude, h.Longitude, h.TagID}
}

func (History) IsGenerated(c string) bool {
	switch c {
	case "id":
		return true
	}
	return false
}

func (h History) Values() []sql.NamedArg {
	return []sql.NamedArg{sql.Named("id", h.ID), sql.Named("time", h.Time), sql.Named("speed", h.Speed), sql.Named("altitude", h.Altitude), sql.Named("latitude", h.Latitude), sql.Named("longitude", h.Longitude), sql.Named("tag_id", h.TagID)}
}

func (h *History) ScanFrom(columns []string, rows *sql.Rows, buf []any) error {
	for _, c := range columns {
		switch c {
		case "id":
			buf = append(buf, &h.ID)
		case "time":
			buf = append(buf, &h.Time)
		case "speed":
			buf = append(buf, &h.Speed)
		case "altitude":
			buf = append(buf, &h.Altitude)
		case "latitude":
			buf = append(buf, &h.Latitude)
		case "longitude":
			buf = append(buf, &h.Longitude)
		case "tag_id":
			buf = append(buf, &h.TagID)
		default:
			return fmt.Errorf("unknown column name %q", c)
		}
	}
	return rows.Scan(buf...)
}

func _() {
	// Validate the struct fields haven't changed. If this doesn't compile you probably need to `go generate` again.
	var t Tag
	_ = Tag{t.ID, t.Name, t.Colour}
}

func (Tag) IsGenerated(c string) bool {
	switch c {
	case "id":
		return true
	}
	return false
}

func (t Tag) Values() []sql.NamedArg {
	return []sql.NamedArg{sql.Named("id", t.ID), sql.Named("name", t.Name), sql.Named("colour", t.Colour)}
}

func (t *Tag) ScanFrom(columns []string, rows *sql.Rows, buf []any) error {
	for _, c := range columns {
		switch c {
		case "id":
			buf = append(buf, &t.ID)
		case "name":
			buf = append(buf, &t.Name)
		case "colour":
			buf = append(buf, &t.Colour)
		default:
			return fmt.Errorf("unknown column name %q", c)
		}
	}
	return rows.Scan(buf...)
}
