// Code generated by "sqlbgen History"; DO NOT EDIT.

package main

import (
	"database/sql"
	"fmt"
)

func _() {
	// Validate the struct fields haven't changed. If this doesn't compile you probably need to `go generate` again.
	var h History
	_ = History{h.ID, h.Speed, h.Altitude, h.Latitude, h.Longitude}
}

func (History) PrimaryKey() string {
	return "id"
}

func (h History) Values() []sql.NamedArg {
	return []sql.NamedArg{sql.Named("id", h.ID), sql.Named("speed", h.Speed), sql.Named("altitude", h.Altitude), sql.Named("latitude", h.Latitude), sql.Named("longitude", h.Longitude)}
}

func (h *History) ScanFrom(rows *sql.Rows) error {
	columns, err := rows.Columns()
	if err != nil {
		return err
	}
	dests := make([]any, 0, len(columns))
	for _, c := range columns {
		switch c {
		case "id":
			dests = append(dests, &h.ID)
		case "speed":
			dests = append(dests, &h.Speed)
		case "altitude":
			dests = append(dests, &h.Altitude)
		case "latitude":
			dests = append(dests, &h.Latitude)
		case "longitude":
			dests = append(dests, &h.Longitude)
		default:
			return fmt.Errorf("unknown column name %q", c)
		}
	}
	return rows.Scan(dests...)
}
